import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section>
          <div className="headline">
            <h1>
              Inga Patricia Traub
              <br />
              ---------
            </h1>
            <div className="portfolio">
              <h3>portfolio</h3>
            </div>
          </div>
        </section>
        <section>
          <div className="about">
            <div className="mypic"></div>
            <h2>About</h2>
            <p>
              Hey, I am Inga, 29 years old and a recent graduate of the 5th Code
              & Design Camp of DevHaus Leipzig. Before that I was half student
              half musician and producer. Corona has changed the lives of many
              people and mine as well. In summer 2019 I decided to give up my
              studies of musicology to focus on making music. During the
              pandemic my plan failed and I felt the urge to learn something
              completely new. And it seems like I did.. what you’re looking at
              is my first website.
            </p>
            <p>I'm currently looking for jobs. Feel free to contact me!</p>
          </div>
        </section>
      </main>
    </div>
  );
};

export default Home;
